from app.engines.cash_ledger_engine.parsers.parser import (
    is_auditable_transaction_row,
    is_cash_ledger_footer_row,
    is_report_total_row,
)


def test_is_report_total_row_detects_grand_total() -> None:
    row = {
        'date': None,
        'voucher_no': None,
        'branch': None,
        'contra_account': None,
        'debit': '562,562,210.00',
        'credit': '551,859,678.00',
        'balance': None,
    }
    assert is_report_total_row(row) is True
    assert is_auditable_transaction_row(row) is False


def test_is_auditable_transaction_row_accepts_real_transaction() -> None:
    row = {
        'date': '01-04-2025',
        'voucher_no': 'V001',
        'branch': 'HQ',
        'contra_account': 'Sales',
        'debit': 250000,
        'credit': None,
        'balance': '2,50,000 Dr',
    }
    assert is_auditable_transaction_row(row) is True
    assert is_report_total_row(row) is False


def test_is_auditable_transaction_row_accepts_contra_only_identifier() -> None:
    row = {
        'date': None,
        'voucher_no': None,
        'contra_account': 'Opening Balance',
        'debit': 1000,
        'credit': None,
        'balance': '1,000 Dr',
    }
    assert is_auditable_transaction_row(row) is True


def test_is_cash_ledger_footer_row_date_prefix() -> None:
    assert is_cash_ledger_footer_row(['Date : 04/07/2026 11:32 AM', None, None]) is True
    assert is_cash_ledger_footer_row({'date': 'Date: 04/07/2026', 'voucher_no': None}) is True


def test_is_cash_ledger_footer_row_user_name() -> None:
    assert is_cash_ledger_footer_row(['User Name : H A A']) is True
    assert is_cash_ledger_footer_row(['Printed By : Admin']) is True
    assert is_cash_ledger_footer_row(['Generated By : System']) is True
    assert is_cash_ledger_footer_row(['Report Generated on server']) is True


def test_is_cash_ledger_footer_row_ignores_normal_date() -> None:
    assert is_cash_ledger_footer_row(['01-04-2025', 'V001', 'Sales']) is False
    assert is_cash_ledger_footer_row({'date': '01-04-2025', 'voucher_no': 'V001'}) is False
