"""Parser utilities for Cash Ledger Audit."""

import re
from typing import Any, Sequence, Tuple

# Footer markers from Tally/ERP Cash Ledger exports (case-insensitive prefix match).
_FOOTER_PREFIXES = (
    'date :',
    'date:',
    'user name',
    'printed by',
    'generated by',
    'report generated',
)


def is_empty_field(value: Any) -> bool:
    """Return True when a ledger cell has no meaningful content."""
    if value is None:
        return True
    if isinstance(value, float) and value != value:  # NaN
        return True
    return not str(value).strip()


def _cell_text(value: Any) -> str:
    if is_empty_field(value):
        return ''
    return str(value).replace('\n', ' ').replace('\r', ' ').strip()


def is_cash_ledger_footer_row(row: Sequence[Any] | dict[str, Any]) -> bool:
    """
    Detect report footer metadata rows that appear after the last transaction.

    Matches first-column (or first non-empty cell) prefixes such as:
    Date :, User Name, Printed By, Generated By, Report Generated.
    """
    if isinstance(row, dict):
        cells: list[Any] = list(row.values())
    else:
        cells = list(row)

    first_text = ''
    for cell in cells:
        text = _cell_text(cell)
        if text:
            first_text = text
            break

    if not first_text:
        return False

    lowered = first_text.lower()
    return any(lowered.startswith(prefix) for prefix in _FOOTER_PREFIXES)


def is_auditable_transaction_row(row: dict[str, Any]) -> bool:
    """
    Return True when a row represents a real ledger transaction.

    Grand total / summary rows (and other non-transaction rows) lack date,
    voucher number, and contra account. They must be excluded before audit rules run.
    """
    if is_report_total_row(row):
        return False
    if is_cash_ledger_footer_row(row):
        return False
    return any(
        not is_empty_field(row.get(field))
        for field in ('date', 'voucher_no', 'contra_account')
    )


def is_report_total_row(row: dict[str, Any]) -> bool:
    """
    Detect report grand-total rows.

    These rows only carry debit/credit totals while date, voucher no,
    contra account, and balance are all empty.
    """
    identity_empty = all(
        is_empty_field(row.get(field))
        for field in ('date', 'voucher_no', 'contra_account', 'balance')
    )
    if not identity_empty:
        return False
    return (
        parse_amount(row.get('debit')) is not None
        or parse_amount(row.get('credit')) is not None
    )


def parse_amount(amount_str: str | None) -> float | None:
    """
    Convert formatted amount string to numeric value.

    Examples:
        '11,23,145.00' -> 1123145.00
        '95,000' -> 95000.0
        '500' -> 500.0
        None -> None
        '' -> None
    """
    if not amount_str or str(amount_str).strip() == '':
        return None

    # Remove commas and whitespace
    cleaned = str(amount_str).replace(',', '').strip()

    # Remove any non-numeric characters except decimal point and negative sign
    cleaned = re.sub(r'[^\d.\-]', '', cleaned)

    if not cleaned or cleaned == '.' or cleaned == '-':
        return None

    try:
        return float(cleaned)
    except (ValueError, TypeError):
        return None


def parse_balance(balance_str: str | None) -> Tuple[float | None, str | None]:
    """
    Extract numeric value and Dr/Cr type from balance string.

    Examples:
        '1,12,33,145 Dr' -> (11233145.0, 'DR')
        '95,000 Cr' -> (95000.0, 'CR')
        '500' -> (500.0, None)
        '-2500' -> (-2500.0, None)
        None -> (None, None)
    """
    if not balance_str or str(balance_str).strip() == '':
        return None, None

    balance_str = str(balance_str).strip().upper()

    # Detect Dr/Cr
    balance_type = None
    if 'DR' in balance_str:
        balance_type = 'DR'
        balance_str = balance_str.replace('DR', '').strip()
    elif 'CR' in balance_str:
        balance_type = 'CR'
        balance_str = balance_str.replace('CR', '').strip()

    # Parse numeric value
    numeric_value = parse_amount(balance_str)

    return numeric_value, balance_type
