export const TDS_RULE_BOOK_SECTIONS = [
  {
    section: '194A',
    description: 'Interest other than Interest on Securities',
    threshold: 'Rs. 10,000 per annum',
    rate: '10%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194C',
    description: 'Payments to resident contractor/sub-contractor',
    threshold: 'Rs. 30,000 per transaction or Rs. 1,00,000 per annum',
    rate: null,
    rate_individual: '1%',
    rate_others: '2%',
    special_rule: null,
  },
  {
    section: '194J(a)',
    description: 'Fees for Technical Services',
    threshold: 'Rs. 50,000 per annum',
    rate: '2%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194J(b)',
    description: 'Fees for Professional Services',
    threshold: 'Rs. 50,000 per annum',
    rate: '10%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194J(1)(ba)',
    description: "Director's Remuneration",
    threshold: 'No Threshold',
    rate: '10%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194I(a)',
    description: 'Rent of Plant & Machinery',
    threshold: 'Rs. 50,000 per month or part of a month',
    rate: '2%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194I(b)',
    description: 'Rent of Land & Building',
    threshold: 'Rs. 50,000 per month or part of a month',
    rate: '10%',
    rate_individual: null,
    rate_others: null,
    special_rule: null,
  },
  {
    section: '194Q',
    description: 'Purchase of goods from a resident seller (Buyer\'s turnover > Rs.10 Crore)',
    threshold: 'Rs. 50,00,000 per annum',
    rate: '0.1%',
    rate_individual: null,
    rate_others: null,
    special_rule: 'If PAN is not available, use 5%',
  },
];

export const TDS_SECTION_CODES = TDS_RULE_BOOK_SECTIONS.map((s) => s.section);
